#!/bin/bash

function install_haproxy() {
    local pkg=haproxy-${HAPROXY_VERSION}.tar.gz

    mkdir -p ${OPENSHIFT_RUNTIME_DIR}/etc/haproxy
    mkdir -p ${BUILD_DIR}
    pushd ${BUILD_DIR}

    if [ ! -f ${pkg} ]; then
	echo "Downloading ${pkg}."
	wget http://bcs.duapp.com/instcar-vedio/haproxy/${pkg}
    fi

    if [ ! -d haproxy-${HAPROXY_VERSION} ]; then
	echo "Unpacking ${pkg}."
	tar xfz ${pkg}
    fi
    
    pushd haproxy-${HAPROXY_VERSION}
    
    echo "Configuring HaProxy."
    make \
       TARGET=linux26 

    echo "Compiling HaProxy."
    make install \
       PREFIX=${ROOT_DIR}/haproxy/

    echo "Cleaning build directory."
    popd
    popd
    rm -rf ${BUILD_DIR}
}

function check_haproxy() {
    local local_bin=/usr/bin/haproxy
    local haproxy_bin=${ROOT_DIR}/haproxy/sbin/haproxy

    if [[ -e  ${local_bin} ]]; then
	local haproxy_version=`${local_bin} -v | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'`
        if [[ ${HAPROXY_VERSION} = ${haproxy_version} ]]; then
            echo "HaProxy local will be used"
            return 0
        fi
        echo "HaProxy local old, version: ${haproxy_version}."
    fi

    if [[ ! -e  ${haproxy_bin} ]]; then
        echo "HaProxy not installed."
        install_haproxy
    else
        haproxy_version=`${haproxy_bin} -v | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'`

        if [[ ${HAPROXY_VERSION} != ${haproxy_version} ]]; then
            echo "HaProxy old, version: ${haproxy_version}."
            install_haproxy
        else
            echo "HaProxy up to date, version: ${haproxy_version}."
        fi
    fi
}

