#!/bin/bash

function install_mysql() {
    local pkg=mysql-${MYSQL_VERSION}.tar.gz

    mkdir -p ${BUILD_DIR}
    pushd ${BUILD_DIR}

    if [ ! -f ${BUILD_DIR}/${pkg} ]; then
       echo "Downloading ${pkg}."
       wget http://bcs.duapp.com/instcar-vedio/mysql/${pkg}
    fi

    if [ ! -d mysql-${MYSQL_VERSION} ]; then
        echo "Unpacking ${pkg}."
    	tar xfz ${pkg}
    fi

    pushd mysql-${MYSQL_VERSION}
    
    if [ ! -d build ]; then
       mkdir build
    fi
    
    cd build
    echo "Configuring MySQL."
    cmake .. \
       -DCMAKE_INSTALL_PREFIX=/mysql 

    echo "Compiling MySQL."
    make
    make install \
       DESTDIR=${ROOT_DIR}
    cd ..
    
    echo "Cleaning build directory."
    popd
    popd
    rm -rf ${BUILD_DIR}
}

function check_mysql() {
    local local_bin=/usr/bin/mysql
    local mysql_bin=${ROOT_DIR}/mysql/bin/mysql

    if [[ -e  ${local_bin} ]]; then
        local mysql_version=`${local_bin} --version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'`    
        if [[ ${MYSQL_VERSION} = ${mysql_version} ]]; then
            echo "MySQL local will be used"
            return 0
        fi
        echo "MySQL local old, version: ${mysql_version}."
    fi

    if [[ ! -e  ${mysql_bin} ]]; then
        echo "MySQL not installed."
        install_mysql
    else
        mysql_version=`${mysql_bin} --version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'`

        if [[ ${MYSQL_VERSION} != ${mysql_version} ]]; then
            echo "MySQL old, version: ${mysql_version}."
            install_mysql
        else
            echo "MySQL up to date, version: ${mysql_version}."
        fi
    fi
}

