#!/bin/bash

source ${OPENSHIFT_REPO_DIR}/openshift/action_hooks/common

echo "Stopping nginx."
if [ -f ${OPENSHIFT_RUN_DIR}/nginx.pid ];then
    kill -QUIT `cat ${OPENSHIFT_RUN_DIR}/nginx.pid`
else
    kill -9 `lsof -t -i :8080`
fi

echo "Stopping PHP-fpm."
if [ -f ${OPENSHIFT_RUN_DIR}/php-fpm.pid ];then
    kill -QUIT `cat ${OPENSHIFT_RUN_DIR}/php-fpm.pid`
fi

echo "Stopping MySQL."

if [ -f ${OPENSHIFT_RUN_DIR}/mysql.pid ]; then
    pushd ${OPENSHIFT_RUNTIME_DIR}/mysql
    ./mysql.server stop
    popd
fi

echo "Stopping Redis."

if [ -f ${OPENSHIFT_RUN_DIR}/redis_${OPENSHIFT_REDIS_DIR}.pid ]; then
    pushd ${OPENSHIFT_RUNTIME_DIR}/redis
    ./redis_${OPENSHIFT_REDIS_PORT} stop
    popd
fi

echo "Stopping HaProxy."

if [ -f ${OPENSHIFT_RUN_DIR}/haproxy.pid ]; then
    pushd ${OPENSHIFT_RUNTIME_DIR}/haproxy
    sudo ./haproxy.server stop
    popd
fi


# Always succeed, otherwise OpenShift declines to run build and start
# hooks.
exit 0
