#!/bin/bash

# Exit on first error.
set -e

umask 077


# Ubuntu only
sudo apt-get -y install build-essential
sudo apt-get -y install libssl-dev
sudo apt-get -y install libcurl4-openssl-dev
sudo apt-get -y install libxslt-dev
sudo apt-get -y install libmcrypt-dev
sudo apt-get -y install libbz2-dev
sudo apt-get -y install libpng12-dev
sudo apt-get -y install libjpeg8-dev
sudo apt-get -y install libreadline-dev

OPENSHIFT_HOOK_DIR=`dirname $0`
export OPENSHIFT_REPO_DIR=$OPENSHIFT_HOOK_DIR/../../
export OPENSHIFT_DIY_DIR=${1}
export OPENSHIFT_TMP_DIR=${1}/tmp/

echo $OPENSHIFT_REPO_DIR
echo $OPENSHIFT_DIY_DIR
echo $OPENSHIFT_TMP_DIR

# Load common
source ${OPENSHIFT_REPO_DIR}/openshift/action_hooks/common

# Configure versions
NGINX_VERSION='1.5.1'
ZLIB_VERSION='1.2.8'
PCRE_VERSION='8.33'

PHP_VERSION='5.5.8'
ICU_VERSION='51.2'

LIBMCRYPT_VERSION='2.5.8'
LIBTOOL_VERSION='2.4.2'

NODE_VERSION='0.6.20' #'0.10.12'

declare -A PHP_PECL
declare -A PHP_PECL_CONFIGURE
PHP_PECL=( ["mongo"]='1.4.1' )
PHP_PECL_CONFIGURE=( )


# Setup dir references
export ROOT_DIR=${OPENSHIFT_RUNTIME_DIR}
export BUILD_DIR=${OPENSHIFT_TMP_DIR}/build
export CONFIG_DIR=${OPENSHIFT_DIY_DIR}/conf
export TEMPLATE_DIR=${OPENSHIFT_REPO_DIR}/openshift/tmpl

# Load functions
source ${OPENSHIFT_REPO_DIR}/openshift/action_hooks/build_nginx
source ${OPENSHIFT_REPO_DIR}/openshift/action_hooks/build_php_libs
source ${OPENSHIFT_REPO_DIR}/openshift/action_hooks/build_php
#source ${OPENSHIFT_REPO_DIR}/openshift/action_hooks/build_node

# Check nginx
check_nginx

# Check PHP
check_php

# Check pecl extensions
for ext in "${!PHP_PECL[@]}"; do
    check_pecl ${ext} ${PHP_PECL["$ext"]} ${PHP_PECL_CONFIGURE["$ext"]};
done

# Check NodeJS
#check_node
