#!/bin/bash

set -e

source ${OPENSHIFT_REPO_DIR}/openshift/action_hooks/common

BUILD_DIR=${OPENSHIFT_TMP_DIR}/build
NGINX_DIR=${OPENSHIFT_RUNTIME_DIR}/nginx/
PHP_DIR=${OPENSHIFT_RUNTIME_DIR}/php5/
MYSQL_DIR=${OPENSHIFT_RUNTIME_DIR}/mysql/
REDIS_DIR=${OPENSHIFT_RUNTIME_DIR}/redis
TEMPLATE_DIR=${OPENSHIFT_REPO_DIR}/openshift/tmpl

umask 077

mkdir -p ${BUILD_DIR}

if [ ! -d ${OPENSHIFT_DIY_LOG_DIR} ]; then
    mkdir -p ${OPENSHIFT_DIY_LOG_DIR}
fi

if [ ! -d ${OPENSHIFT_DATA_DIR} ]; then
    mkdir -p ${OPENSHIFT_DATA_DIR}
fi 

if [ ! -d ${OPENSHIFT_RUN_DIR} ]; then
    mkdir -p ${OPENSHIFT_RUN_DIR}
fi 

echo "Pre-processing nginx config."
cp ${TEMPLATE_DIR}/nginx.conf.tmpl ${BUILD_DIR}/nginx.conf
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}/nginx.conf
cp ${BUILD_DIR}/nginx.conf ${NGINX_DIR}/conf/nginx.conf

echo "Pre-processing PHP-fpm config."
cp ${TEMPLATE_DIR}/php-fpm.conf.tmpl ${BUILD_DIR}/php-fpm.conf
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}/php-fpm.conf
cp ${BUILD_DIR}/php-fpm.conf ${PHP_DIR}/etc/php-fpm.conf

echo "Pre-processing MySQL config."
cp ${TEMPLATE_DIR}/mysql.cnf.tmpl ${BUILD_DIR}/my.cnf
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}/my.cnf
cp ${BUILD_DIR}/my.cnf ${MYSQL_DIR}/my.cnf

cp ${TEMPLATE_DIR}/mysql.server.tmpl ${BUILD_DIR}/mysql.server
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}/mysql.server
cp ${BUILD_DIR}/mysql.server ${MYSQL_DIR}/mysql.server

if [ ! -d ${OPENSHIFT_RUNTIME_DIR}/mysql/data/mysql ]; then
    pushd ${MYSQL_DIR}
    chmod +x mysql.server
    ./scripts/mysql_install_db --defaults-file=${MYSQL_DIR}/my.cnf
    popd
fi


echo "Pre-processing Redis config."
cp ${TEMPLATE_DIR}/redis.conf.tmpl ${BUILD_DIR}/redis.conf
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}/redis.conf
cp ${BUILD_DIR}/redis.conf ${OPENSHIFT_RUNTIME_DIR}/etc/redis/redis_${OPENSHIFT_REDIS_PORT}.conf

cp ${TEMPLATE_DIR}/redis_init_script.tmpl ${BUILD_DIR}/redis_init_script
perl -p -i -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg' ${BUILD_DIR}/redis_init_script
cp ${BUILD_DIR}/redis_init_script ${REDIS_DIR}/redis_${OPENSHIFT_REDIS_PORT}

pushd ${REDIS_DIR}
chmod +x redis_${OPENSHIFT_REDIS_PORT}
popd

rm -rf ${BUILD_DIR}

bash_profile=${OPENSHIFT_DATA_DIR}/.bash_profile
echo "Copy bash profile."
cp ${TEMPLATE_DIR}/bash_profile.tmpl ${bash_profile}
