#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

set -e

source ${OPENSHIFT_REPO_DIR}/openshift/action_hooks/common

MYSQL_DIR=${OPENSHIFT_RUNTIME_DIR}/mysql/

echo "Starting nginx."
${OPENSHIFT_RUNTIME_DIR}/nginx/sbin/nginx

echo "Starting php-fpm."
${OPENSHIFT_RUNTIME_DIR}/php5/sbin/php-fpm

echo "Starting MySQL."
pushd ${MYSQL_DIR}
./mysql.server start
popd
